### ISSUE TITLE
[ERROR DRT-0218] Guide is not connected to design

### ISSUE THREAD

**Issue by Manarabdelaty** [The-OpenROAD-Project/OpenROAD#1360] opened 2021-11-28 16:31 UTC
We are getting this warning on some of the sram pins: 
```
[WARNING DRT-1001] No guide in the pin neighborhood
[WARNING DRT-0215] Pin genblk1\[1\].RAM/dout0[22] not covered by guide.
[WARNING DRT-0215] Pin genblk1\[1\].RAM/dout0[22] not covered by guide.
[WARNING DRT-0225] sram_rdata\[1\]\[22\] 2 pin not visited, fall back to feedthrough mode.
[WARNING DRT-0224] sram_rdata\[1\]\[22\] 2 pin not visited, number of guides = 6.
```

Then, the detailed router fails with this error 

`[ERROR DRT-0218] Guide is not connected to design.
`

Tested with openroad commit: `934e0cc13d8d24ca477f5dfd26b64b232065951a`
[sram_droute_packaged.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/7613904/sram_droute_packaged.zip)

**Comment by maliberty** [comment] 2021-11-28 19:24
@eder-matheus I assume the issue is in grt not drt; if you find otherwise please assign it back.

**Comment by eder-matheus** [comment] 2021-11-29 17:23
@Manarabdelaty could you attach the groute_package for this run?

**Comment by Manarabdelaty** [comment] 2021-11-29 18:59
@eder-matheus Here it is
[sram_groute_packaged.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/7620488/sram_groute_packaged.zip)

**Comment by eder-matheus** [comment] 2021-11-29 20:11
@maliberty The pin with the error is not being covered by the guide because the pin geometry intersects with a single track, only at its right boundary. Check the figure below:
![image](https://user-images.githubusercontent.com/43450810/143933918-dbd5f916-aa7a-4c21-9861-eb5a4ff108e3.png)

grt is computing the position on the routing grid for this pin based on this single track, and this position generates a guide that is not covering the pin. Check this other figure:
![image](https://user-images.githubusercontent.com/43450810/143934238-4fc9673b-3350-4142-be1f-db8ac9b5b815.png)

This is a perfect example of the mismatch between drt pin access and grt "pin to grid". I can workaround this issue by ignoring the track position for IO and macro pins, but a better correlation between grt and drt will still be needed.

**Comment by eder-matheus** [comment] 2021-11-29 20:19
@maliberty When I ignore the position of the tracks for IO and macro pins, the generated guides are valid for TR, which ends with 1 DRCs.

**Comment by maliberty** [comment] 2021-11-29 21:11
@eder-matheus I agree about grt/drt PA (topic for tomorrow's mtg).  
@Manarabdelaty is this urgent or can it wait a while for a better solution?

**Comment by Manarabdelaty** [comment] 2021-11-30 12:52
@maliberty We have a workaround for now to get around this issue (flipping some of the macros helped avoid hitting this error).

**Comment by jameyhicks** [comment] 2022-01-11 21:23
@Manarabdelaty what is the workaround? I've run into this problem also.

**Comment by tspyrou** [comment] 2022-01-12 20:08
@eder-matheus it looks like the workaround is not working, @donn mentioned this today.
Please take a look at this.
A possible workaround might be to run the pin_access command before GR.

**Comment by eder-matheus** [comment] 2022-01-25 15:29
I've fixed a small bug in the `grt` code that uses the access points from `drt`. I've tested the falling design running the `pin_access` command and it is working properly now.

**Closed** 2022-01-25 19:10 UTC
