### ISSUE TITLE
Diode insertion appears to insert diodes in illegal positions

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenROAD#1419] opened 2021-12-13 16:01 UTC
OpenROAD e9bd11509b1d907cbc3205e17f699ef05ae2181c via OpenLane

```
[etc]
Notice 0: Split top of 1 T shapes.
Notice 0: Split top of 2 T shapes.
Notice 0: Split top of 1 T shapes.
Notice 0: Split top of 1 T shapes.
Notice 0: Split top of 1 T shapes.
Notice 0: Split top of 1 T shapes.
Notice 0: Split top of 1 T shapes.
[INFO GRT-0012] Antenna violations: 13
[INFO GRT-0015] 13 diodes inserted.
[WARNING DPL-0005] Overlap check failed (4).
[ERROR DPL-0033] detailed placement checks failed.
Error: groute.tcl, 74 DPL-0033
```

Reproducible:
[groute.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/7705111/groute.tar.gz)

**Comment by tspyrou** [comment] 2021-12-13 16:58
@eder-matheus if this is a detailed placement problem please let me know and I will pass it along to cherry.

**Comment by maliberty** [comment] 2021-12-13 19:24
I have a fix for this that I'm testing now.  The problem is antenna repair only looks at global padding not padding by master type.

**Comment by maliberty** [comment] 2021-12-13 19:59
Fixed with https://github.com/The-OpenROAD-Project/OpenROAD/pull/1421

**Closed by maliberty** 2021-12-13 19:59 UTC
Labels: bug
