### ISSUE TITLE
dependency installer fails in Ubuntu20.04

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD#4035] opened 2023-09-25 07:28 UTC
### Describe the bug

As equivalence check added in OpenROAD, trying to install those with `sudo ./etc/DependencyInstaller.sh`. but it fails to complete the installation.

### Expected Behavior

Complete the Dependency installation.

### Environment

```shell
Git commit: d0bd5cb959f6655f3efbca11572b24a3f5f3e12e
kernel: Linux 5.15.0-84-generic
os: Ubuntu 20.04.6 LTS (Focal Fossa)
cmake version 3.25.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OpenROAD version: v2.0-10415-gd0bd5cb95
-- System name: Linux
-- Compiler: GNU 9.4.0
-- Build type: RELEASE
-- Install prefix: /usr/local
-- C++ Standard: 17
-- C++ Standard Required: ON
-- C++ Extensions: OFF
-- The C compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python: /usr/local/bin/python3.5 (found version "3.5.0") found components: Interpreter 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test C_COMPILER_SUPPORTS__-Wall
-- Performing Test C_COMPILER_SUPPORTS__-Wall - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wall
-- Performing Test CXX_COMPILER_SUPPORTS__-Wall - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-array-bounds
-- Performing Test C_COMPILER_SUPPORTS__-Wno-array-bounds - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-array-bounds
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-array-bounds - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-nonnull
-- Performing Test C_COMPILER_SUPPORTS__-Wno-nonnull - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-nonnull
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-nonnull - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-maybe-uninitialized
-- Performing Test C_COMPILER_SUPPORTS__-Wno-maybe-uninitialized - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-maybe-uninitialized
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-maybe-uninitialized - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-format-overflow
-- Performing Test C_COMPILER_SUPPORTS__-Wno-format-overflow - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-format-overflow
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-format-overflow - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-variable
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-variable - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-variable
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-variable - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-function
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-function - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-function
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-function - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-write-strings
-- Performing Test C_COMPILER_SUPPORTS__-Wno-write-strings - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-write-strings
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-write-strings - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-sign-compare
-- Performing Test C_COMPILER_SUPPORTS__-Wno-sign-compare - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-sign-compare
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-sign-compare - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-deprecated
-- Performing Test C_COMPILER_SUPPORTS__-Wno-deprecated - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-deprecated
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-deprecated - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-c++11-narrowing
-- Performing Test C_COMPILER_SUPPORTS__-Wno-c++11-narrowing - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-c++11-narrowing
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-c++11-narrowing - Failed
-- Performing Test C_COMPILER_SUPPORTS__-Wno-register
-- Performing Test C_COMPILER_SUPPORTS__-Wno-register - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-register
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-register - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-format
-- Performing Test C_COMPILER_SUPPORTS__-Wno-format - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-format
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-format - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-reserved-user-defined-literal
-- Performing Test C_COMPILER_SUPPORTS__-Wno-reserved-user-defined-literal - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-reserved-user-defined-literal
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-reserved-user-defined-literal - Failed
-- Performing Test C_COMPILER_SUPPORTS__-fpermissive
-- Performing Test C_COMPILER_SUPPORTS__-fpermissive - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-fpermissive
-- Performing Test CXX_COMPILER_SUPPORTS__-fpermissive - Success
-- Performing Test C_COMPILER_SUPPORTS__-x
-- Performing Test C_COMPILER_SUPPORTS__-x - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-x
-- Performing Test CXX_COMPILER_SUPPORTS__-x - Failed
-- Performing Test C_COMPILER_SUPPORTS__c++
-- Performing Test C_COMPILER_SUPPORTS__c++ - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__c++
-- Performing Test CXX_COMPILER_SUPPORTS__c++ - Failed
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-but-set-variable
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-but-set-variable - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-but-set-variable
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-but-set-variable - Success
-- TCL library: /usr/local/lib/libtcl.so
-- TCL header: /usr/local/include/tcl.h
-- TCL readline library: /usr/lib/x86_64-linux-gnu/libtclreadline.so
-- TCL readline header: /usr/include/x86_64-linux-gnu
-- Found SWIG: /usr/bin/swig4.0 (found suitable version "4.0.1", minimum required is "3.0")  
-- Found Boost: /usr/local/lib/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0")  
-- boost: 1.76.0
-- Found Python3: /usr/local/include/python3.5m (found version "3.5.0") found components: Development Development.Module Development.Embed 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- spdlog: 1.8.1
-- Found BISON: /usr/bin/bison (found version "3.5.1") 
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.17") found components: doxygen dot 
-- STA version: 2.4.0
-- STA git sha: 7cf916ba205115a06c4531a044ced481f1ff8f12
-- System name: Linux
-- Compiler: GNU 9.4.0
-- Build type: RELEASE
-- Build CXX_FLAGS: -O3 -DNDEBUG
-- Install prefix: /usr/local
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- TCL library: /usr/local/lib/libtcl.so
-- TCL header: /usr/local/include/tcl.h
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- SSTA: 0
-- STA executable: /home/vijayan/OpenROAD-flow/Aug18_OpenROAD/OpenROAD/src/sta/app/sta
-- GPU is not enabled
-- TCL library: /usr/local/lib/libtcl.so
-- TCL header: /usr/local/include/tcl.h
-- Found re2: /opt/or-tools/lib/cmake/re2/re2Config.cmake (found version "9.0.0") 
-- Found Clp: /opt/or-tools/lib/cmake/Clp/ClpConfig.cmake (found version "1.17.7") 
-- Found Cbc: /opt/or-tools/lib/cmake/Cbc/CbcConfig.cmake (found version "2.10.7") 
-- Found Eigen3: /usr/local/share/eigen3/cmake/Eigen3Config.cmake (found version "3.3.9") 
-- Found SCIP: /opt/or-tools/lib/cmake/scip/scip-config.cmake (found version "8.0.1") 
-- GUI is enabled
-- Charts widget is not enabled
-- Found Boost: /usr/local/lib/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0") found components: serialization 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Could NOT find VTune (missing: VTune_LIBRARIES VTune_INCLUDE_DIRS) 
-- Found Boost: /usr/local/lib/cmake/Boost-1.80.0/BoostConfig.cmake (found suitable version "1.80.0", minimum required is "1.78")  
-- TCL library: /usr/local/lib/libtcl.so
-- TCL header: /usr/local/include/tcl.h
-- Found Boost: /usr/local/lib/cmake/Boost-1.80.0/BoostConfig.cmake (found version "1.80.0") found components: serialization system thread 
-- TCL readline enabled
-- Tcl Extended disabled
-- Python3 enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmp.29s4QgMl51
```

### To Reproduce

`sudo ./etc/DependencyInstaller.sh`

### Relevant log output

```shell
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 0cc2ff0 Merge pull request #46 from YosysHQ/jix/dependent-shell-pattern-escape
yosys-config --build src/eqy_combine.so  src/eqy_combine.cc 
yosys-config --build src/eqy_partition.so  src/eqy_partition.cc 
src/eqy_partition.cc:24:10: fatal error: kernel/json.h: No such file or directory
   24 | #include "kernel/json.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:29: src/eqy_partition.so] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by gudeh** [comment] 2023-09-25 16:48
I am having the same issue here. I am using "sudo ./setup.sh":

```
0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.
CMake already installed.
Swig already installed.
Boost already installed.
Eigen already installed.
CUSP already installed.
Lemon already installed.
spdlog already installed.
Cloning into 'eqy'...
remote: Enumerating objects: 1720, done.
remote: Counting objects: 100% (183/183), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 1720 (delta 63), reused 74 (delta 42), pack-reused 1537
Receiving objects: 100% (1720/1720), 1.04 MiB | 4.92 MiB/s, done.
Resolving deltas: 100% (1100/1100), done.
Note: switching to '0cc2ff0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 0cc2ff0 Merge pull request #46 from YosysHQ/jix/dependent-shell-pattern-escape
yosys-config --build src/eqy_combine.so  src/eqy_combine.cc 
yosys-config --build src/eqy_partition.so  src/eqy_partition.cc 
yosys-config --build src/eqy_recode.so  src/eqy_recode.cc 
src/eqy_partition.cc:24:10: fatal error: kernel/json.h: No such file or directory
   24 | #include "kernel/json.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:29: src/eqy_partition.so] Error 1
make: *** Waiting for unfinished jobs....
```

The error message seems to be the same.

**Comment by vvbandeira** [comment] 2023-09-25 17:20
I cannot reproduce the error using the latest version of OR and a clean image from Docker. I will spin up a VM later to see if there's any difference, but it is unlikely. @vijayank88 can you manually install `eqy`?

**Comment by gadfort** [comment] 2023-09-25 20:39
@vvbandeira @vijayank88 would it be possible to make yosys, sbu, eqy compiles and installs optional for runtime use, it seems like a huge overhead to make everyone compile it when its only used in a few CI tests?

**Comment by vvbandeira** [comment] 2023-09-25 21:07
@gadfort, do you think one switch for all three (e.g., `-equivalence`) or would one for each tool be better?

**Comment by gadfort** [comment] 2023-09-25 21:09
@vvbandeira I think one switch would be fine since most folks that would need it will need to install all three.

**Comment by vijayank88** [comment] 2023-09-26 03:01
@vvbandeira 
Currently I'm using this pre-built package of yosys for Centos7/Ubuntu20.04 to avoid installation issue: https://github.com/YosysHQ/oss-cad-suite-build#installation

**Comment by gadfort** [comment] 2023-09-26 21:16
@vvbandeira any updates on this? We are getting similar failures

**Comment by vvbandeira** [comment] 2023-09-26 21:47
@gadfort I have started #4052 to skip `yosys/eqy/sby` installs

**Comment by troibe** [comment] 2023-09-26 22:09
The issue is on a user machine they most likely have yosys maybe installed from a previous install of openroad.
In this case the yosys version might be older than 0.33 which seems to be required for eqy and sby.
The script does not update yosys if it's already installed (a reasonable default).
**Installing yosys 0.33 solved the issue for me.**
If this is only for CI testing then skipping eqy and sby by default sounds like a good idea.

**Comment by vvbandeira** [comment] 2023-09-26 22:18
Thanks for the input @troibe, @vijayank88 could you check if that is the reason why your install is failing?

Currently, we are enabling `eqy` in the CI tests, but the goal is to provide a way for users to run equivalence checks (if the dependencies are available), somewhat like `report_check`.

**Comment by vijayank88** [comment] 2023-09-27 11:00
Thanks @vvbandeira. With latest commit I am not facing any issues while executing `sudo ./etc/DependencyInstaller.sh`.

**Comment by vijayank88** [comment] 2023-09-27 11:23
Is any switch need to be added to install OpenROAD equivalence dependencies yosys/eqy/sby in general during `sudo ./etc/DependencyInstaller.sh` execution?
https://github.com/The-OpenROAD-Project/OpenROAD/blob/347459a5c91f473de611c0c0f403eb4880e8d339/etc/DependencyInstaller.sh#L11

**Comment by vvbandeira** [comment] 2023-09-27 12:27
@vijayank88 
```
./etc/DependencyInstaller.sh -common -eqy
```

**Comment by gudeh** [comment] 2023-09-28 16:02
Hey guys, with the latest changes I was able to run "sudo ./setup.sh" (from ORFS) without any error messages. Although, when I run the flow I am getting the following error:

```
Repair setup and hold violations...
TNS end percent 100
[INFO RSZ-0094] Found 43 endpoints with setup violations.
[INFO RSZ-0040] Inserted 22 buffers.
[INFO RSZ-0041] Resized 107 instances.
[INFO RSZ-0043] Swapped pins on 40 instances.
[INFO RSZ-0049] Cloned 1 instances.
[WARNING RSZ-0062] Unable to repair all setup violations.
[INFO RSZ-0033] No hold violations found.
Error: cts.tcl, 110 couldn't execute "eqy": no such file or directory
Command exited with non-zero status 1
Elapsed time: 0:06.42[h:]min:sec. CPU time: user 6.38 sys 0.03 (99%). Peak memory: 110052KB.
make[1]: *** [Makefile:673: do-4_1_cts] Error 1
make: *** [Makefile:673: results/nangate45/gcd/base/4_1_cts.odb] Error 2
```

Should I create a new issue on ORFS repository with more details (for example the build_openroad.log), or would anyone have a possible easy solution?

Furthermore, as mentioned by @troibe, my Yosys version is 0.33 (as it seems it should be).

**Comment by vvbandeira** [comment] 2024-01-16 11:23
Closing as it is currently working on CI and fixes for `eqy` issues have been merged. Please re-open if the problem persists or start a new issue after testing with the latest code.

**Closed by vvbandeira** 2024-01-16 11:23 UTC
