### ISSUE TITLE
DRT fails to find a path

### ISSUE THREAD

**Issue by VidyaChhabria** [The-OpenROAD-Project/OpenROAD#1853] opened 2022-05-12 21:19 UTC
Hi,

I modified ORFS to add fixes (repair_timing) post GR. The attached testcase fails to find a path between pin and source aps. See below. 

Testcase is at: [detail_route_ibex_asap7_base_2022-05-12_13-20](https://drive.google.com/file/d/1W69BFWmWcHfdh9VmiOq2HBymEksctLlv/view?usp=sharing)

```
[INFO DRT-0195] Start 0th optimization iteration.
Failed to find a path between pin  and source aps:
( 299 195 5 ) (Idx) / ( 3780 60624 ) (coords)
extBBox (xDim, yDim, zDim) = (456, 710, 10)
Failed to find a path between pin  and source aps:
( 3 398 3 ) (Idx) / ( 12 85548 ) (coords)
( 6 398 3 ) (Idx) / ( 60 85548 ) (coords)
( 25 398 3 ) (Idx) / ( 300 85548 ) (coords)
extBBox (xDim, yDim, zDim) = (456, 710, 10)
[ERROR DRT-0255] Maze Route cannot find path of net clk_i in worker of routeBox ( 0 60480 ) ( 3780 64260 ).
[ERROR DRT-0255] Maze Route cannot find path of net clk_i in worker of routeBox ( 0 83160 ) ( 3780 86940 ).
```

**Comment by VidyaChhabria** [comment] 2022-05-12 21:36
@WenjingJiang21 FYI.

**Comment by Stephanommg** [comment] 2022-05-16 23:47
The problem is solved and the fix is going through some tests before it is merged into the master branch.

**Comment by Stephanommg** [comment] 2022-05-18 21:46
The fix is on the master branch now.

**Closed by Stephanommg** 2022-05-18 21:46 UTC
