### ISSUE TITLE
How do I complete the configuration of the "openroad -python" environment on the IDE?

### ISSUE THREAD

**Issue by lazzy-dog** [The-OpenROAD-Project/OpenROAD#4860] opened 2024-03-27 02:52 UTC
### Description

I can enter the command "./openroad -python ./myself_code.py" on the terminal and import openroad in "myself_code.py" for code development. But I cannot run openroad as the environment in the Python interpreter under pycharm, and then use pycharm to complete the development. In other words, I don't know how to run the code "./openroad -python ./myself_code.py" using the IDE.

### Suggested Solution

I tried asking chatgpt but he didn't seem to have a solution.

**Comment by maliberty** [comment] 2024-03-27 02:58
Openroad is the main program and starts its own interpreter.   I don't know how pycharm works but it may assume that it is the main program in which case it is incompatible.  There has been much discussion of making an OR pip module but it hasn't come to fruition.

**Comment by lazzy-dog** [comment] 2024-03-27 03:15
So, ask the teacher. How can I know which APIs are officially provided by Openroad when developing code that relies on the "openroad -python" environment without an IDE? Because I don't seem to find an introduction to the corresponding API in the official documentation.

**Comment by maliberty** [comment] 2024-03-27 03:18
The python API is newer and not totally complete.  I suggest you look at 

https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/include/ord/Design.h
https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/include/ord/Tech.h

which are available in Python as a starting point.  For most modules there are test in python as well that can be used as a guide.  If you have specific needs I can try to help.

**Comment by lazzy-dog** [comment] 2024-03-27 03:27
Thanks for your reply, that will be of great help to me.
And I'm trying to solve the above problem with IDE, I will come back if there are any results.
I hope that like the introduction of "import time", I can find its member functions when I use '.'.
![UBTS{(HIW)11 Y$W3BB7OYT](https://github.com/The-OpenROAD-Project/OpenROAD/assets/62580604/917f780d-9b61-42af-9fcf-52df89f9bcef)

**Comment by maliberty** [comment] 2024-03-27 03:47
I agree that would be very nice.  @proppy any thoughts?

**Comment by oharboe** [comment] 2024-03-27 06:33
> Openroad is the main program and starts its own interpreter. I don't know how pycharm works but it may assume that it is the main program in which case it is incompatible. There has been much discussion of making an OR pip module but it hasn't come to fruition.

Idiomatic Python support requires OR being provided as a PIP module or all sorts of use-cases break.... This is issue is just an example, so in that sense, this issue is a duplicate of #1424

**Comment by maliberty** [comment] 2024-03-27 16:57
No disagreement, just a matter of priorities.

**Comment by maliberty** [comment] 2024-03-27 16:58
I'll close as a dup.  Feel free to reopen if a more specific issue is identified.

**Closed by maliberty** 2024-03-27 16:58 UTC

**Comment by lazzy-dog** [comment] 2024-03-28 02:00
> > Openroad is the main program and starts its own interpreter. I don't know how pycharm works but it may assume that it is the main program in which case it is incompatible. There has been much discussion of making an OR pip module but it hasn't come to fruition.
> 
> Idiomatic Python support requires OR being provided as a PIP module or all sorts of use-cases break.... This is issue is just an example, so in that sense, this issue is a duplicate of #1424
Thanks for your reply, there still doesn't seem to be a convenient solution for issue #1424. I'm trying something new.

**Comment by lazzy-dog** [comment] 2024-03-28 02:01
> I'll close as a dup. Feel free to reopen if a more specific issue is identified.

Thank you for your efforts.
