### ISSUE TITLE
Please remove the requirement of SWIG version 3.0

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenROAD#510] opened 2020-09-14 16:10 UTC
The current SWIG version is 4.0.2 and many systems have only 4.0.2, see https://repology.org/project/swig/versions

I had to apply such patches to build:
```
-find_package(SWIG REQUIRED 3.0)
+find_package(SWIG REQUIRED)
```

README says that ```swig 4.0``` is required.

**Comment by ax3ghazy** [comment] 2020-09-15 11:29
Relevant: https://github.com/The-OpenROAD-Project/OpenROAD/issues/499

**Comment by maliberty** [comment] 2020-09-15 15:43
Duplicate of 499 as noted

**Closed by maliberty** 2020-09-15 15:43 UTC
