### ISSUE TITLE
Synthesis of small circuits

### ISSUE THREAD

**Issue by RatkoFri** [The-OpenROAD-Project/OpenROAD#198] opened 2020-04-07 20:57 UTC
Greetings, 

I am trying to synthesize small circuits like multipliers. In one tool (QFLOW)  my designs exhibit really small energy consumption. On the other hand OpenROAD, I get totally different results. Can you give some tips on how to efficiently synthesize small designs?

Ratko

**Comment by rovinski** [comment] 2020-04-08 05:59
Hi @RatkoFri,

Can you please be more specific about the behavior you are seeing? Can you provide us with the verilog and design configuration inputs? Does the difference show up when targeting the nangate45 library, and if so, can you provide the specific numbers you are seeing?

**Comment by rovinski** [comment] 2020-04-08 06:00
Closing as duplicate of https://github.com/The-OpenROAD-Project/OpenROAD-flow/issues/45

**Closed by rovinski** 2020-04-08 06:00 UTC
