### ISSUE TITLE
Python interface problem

### ISSUE THREAD

**Issue by FuxingHuang** [The-OpenROAD-Project/OpenROAD#5011] opened 2024-04-28 10:58 UTC
### Description

The official way to use the python interface is:
```bash
openroad -python script.py
```
Using the following method will report an error:
```bash
python script.py
```
Because SWIG compiles a static library, not a shared library. Python cannot use static libraries directly.

### Suggested Solution

It would be great if you could use openroad's python package in the same way as other python packages.

**Comment by maliberty** [comment] 2024-04-28 14:55
Duplicate of https://github.com/The-OpenROAD-Project/OpenROAD/issues/2308

**Closed by maliberty** 2024-04-28 14:55 UTC
