### ISSUE TITLE
qt5-default dependency on Ubuntu 22.04

### ISSUE THREAD

**Issue by anthonyjwall** [The-OpenROAD-Project/OpenROAD#2247] opened 2022-09-06 11:15 UTC
Hi,

I'm installing on Ubuntu 22.04, and the etc/DependencyInstaller.sh is failing when trying to install qt5-default. This package is obsolete in ubuntu 22.04 but all its dependencies can be fulfilled with:
sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

Running this above command and commenting out the qt5-default dependency on line 147 of DependencyInstaller.sh allows me to compile and run ok.

Thanks,
Anthony

**Comment by vvbandeira** [comment] 2022-09-06 12:57
Thanks, @anthonyjwall I will try to get to this soon. But I will close this as a duplicate of #1922

**Closed by vvbandeira** 2022-09-06 12:57 UTC

**Comment by anthonyjwall** [comment] 2022-09-06 13:01
Sorry, didn't see #1922! Thanks @vvbandeira!
