### ISSUE TITLE
LVS check is incorrect

### ISSUE THREAD

**Issue by Xies3** [The-OpenROAD-Project/OpenROAD#2326] opened 2022-10-02 02:05 UTC
[6_final_lvs.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/9691486/6_final_lvs.zip)
I run the drc and lvs check where the lvs check is conducted by netgen after running the Makefile in OpenROAD-flow-scripts/flow. There are no errors found in drc while the result of lvs showed that there's a mismatch of circuit 1 and circuit 2. Could you please help me with this problem. Thank you very much. I attached the cdl, gds, makefile, an lvs report.

**Comment by maliberty** [comment] 2022-10-02 04:12
I am not a netgen user and have no idea how to debug problems related to other tools.  If you can point out something that is specifically wrong with the OR output I can take a look at that.  This is not a complete test case and can't be debugged in any case.

**Comment by Xies3** [comment] 2022-10-02 04:55
Yes, so there are still unconnected areas in the generated cdl file.

发自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: Matt Liberty ***@***.***>
发送时间: 2022年10月2日 12:12
收件人: The-OpenROAD-Project/OpenROAD ***@***.***>
抄送: Xies3 ***@***.***>; Author ***@***.***>
主题: Re: [The-OpenROAD-Project/OpenROAD] LVS check is incorrect (Issue #2326)


I am not a netgen user and have no idea how to debug problems related to other tools. If you can point out something that is specifically wrong with the OR output I can take a look at that. This is not a complete test case and can't be debugged in any case.

―

**Comment by maliberty** [comment] 2022-10-02 04:57
That is not enough of a description to take any action.

**Comment by Xies3** [comment] 2022-10-03 03:54
Yes. In the 6_final lvs report, some nets are mismatching and I think that is because some names of instances are not in the library. So is that openroad used some instances that were not in the library and added them to the gds? Thank you very much.

**Comment by maliberty** [comment] 2022-10-03 05:28
What instances?  If you don't give a specific problem don't expect any action.

Also you have not provided a complete test case allowing me to reproduce the result.

**Comment by vijayank88** [comment] 2022-10-03 05:40
@Xies3 
Its good to try this design with `OpenLane flow` https://github.com/The-OpenROAD-Project/OpenLane as it had all signoff checks tools integrated.
If still LVS failures there, file github issue.

**Comment by maliberty** [comment] 2022-10-03 06:26
If the same problem happens in OL the same data will be needed - a specific problem and a complete test case.  I am not clear this is a tool integration issue.  It not clear whether this is a yosys, OR, KLayout, netgen, or user error problem yet.

If you are using ORFS then "make final_report_issue" should package a test case.

**Comment by maliberty** [comment] 2022-10-05 03:21
Please close this if no further action is needed.

**Comment by saicharan0112** [comment] 2022-10-06 16:52
@maliberty This is related to OpenFASOC/temp-sense generator. With the latest version of openroad, the drc check for the generated gds file, the following message is generated 

```
Extracting sky130_fd_sc_hd__decap_4 into sky130_fd_sc_hd__decap_4.ext:
freeMagic called with NULL argument.
```

Also this is reflected in the lvs check where there is a device mismatch for this exact cell.

Please note that this is not observed from the version [2.0_5006_g503c27e77](https://anaconda.org/LiteX-Hub/openroad/2.0_5006_g503c27e77/download/linux-64/openroad-2.0_5006_g503c27e77-20220921_210118.tar.bz2) and earlier, where Magic and Netgen are the latest versions. 

Since the issue is clearly something to do with the openroad version change, do you have any idea for this behaviour with the recent openroad changes (was there any bugfix or something)?

**Comment by saicharan0112** [comment] 2022-10-06 17:06
I have also mentioned this in the skywater-pdk slack and here is the conversation thread - https://open-source-silicon.slack.com/archives/C016YSAP6TZ/p1665075690355409

**Comment by msaligane** [comment] 2022-10-06 17:20
Looks like it is a Magic issue. @saicharan0112 Can you open a github issue in Magic?

**Closed** 2022-10-06 17:21 UTC

**Comment by saicharan0112** [comment] 2022-10-08 02:40
@maliberty As promised, here is the conclusion of this issue. The issue is with the update made to pdn file in https://github.com/The-OpenROAD-Project/OpenROAD/pull/2289 where power connections are done in a different way.
